### ISSUE TITLE
Error on YARN START

### ISSUE THREAD

**Issue by exlnt** [flatlogic/sofia-react-template#1]
I followed the steps in your guide exactly and soon as I run YARN START I get the following error.

> `Failed to compile.
> 
> ./node_modules/react-apexcharts/dist/react-apexcharts.min.js
> Module not found: Can't resolve 'apexcharts/dist/apexcharts.common' in 'D:\Development\UI-Templates\sofia-react-template\node_modules\react-apexcharts\dist'`

**Steps to reproduce:**

1. Git clone the repo
2. YARN (Install all dependencies)
3. YARN START

**Comment by kf1994** [comment]
yarn add react-apexcharts apexcharts

**Comment by yurykurylovich** [comment]
Thanks for the feedback, @exlnt
The problem has been resolved. I added the required library and updated the existing charts libs.
