### ISSUE TITLE
Sidebar disapears after open and close

### ISSUE THREAD

**Issue by R-CoderDotCom** [flatlogic/sofia-react-template#3]
Hi! This dashboard template is really awesome. Congrats!

I was testing it and found an issue with the sidebar and with the search bar. If I open the dashboard on desktop and then I make the screen smaller a burger icon appear. The problem is that if I open the sidebar on a small screen and then I close the menu, if I resize the screen to the desktop size the sidebar disappears.

Open on desktop:
![imagen](https://user-images.githubusercontent.com/67192157/127843725-5da50a98-b504-4d65-ae99-50cd050a00f2.png)

Open and close the menu:
![imagen](https://user-images.githubusercontent.com/67192157/127843782-c1c060bb-8ab2-4a58-a96e-c3481ea9569f.png)

Go back to full screen and the sidebar is gone:
![imagen](https://user-images.githubusercontent.com/67192157/127843809-efc5a520-97c6-4278-aa2f-6176d0a57bff.png)

**Comment by yurykurylovich** [comment]
Hi, @R-CoderDotCom! Thanks for the comment, I fixed this issue. Please, check it out.
