### ISSUE TITLE
Adding New Page

### ISSUE THREAD

**Issue by manal-t07** [flatlogic/sofia-react-template#5]
I am facing difficulty adding a new page to the dashboard. I have resolved the routes in the Layout.js page but still it doesn't show a new page when I add a new folder in pages/

**Comment by yurykurylovich** [comment]
Hello, @manal-t07
I just tried to add a new page to the app and it working great.
You should do these steps:
1. Create your page (don't forget to export it).
2. Add correct Route to the Layout component.
3. Add correct Link to the Sidebar component.
